### ISSUE TITLE
Synchronous Enter and Exit Animations for Cross-Fade Effect

### ISSUE THREAD

**Issue by thmsfchtnr** [ismamz/next-transition-router#12]
Hi there,

First of all, thank you for your fantastic work on this project! I really appreciate the functionality and flexibility it offers.

I’d love to suggest a feature that enables the enter and exit animations to play synchronously. This would allow for a smooth cross-fade effect where the outgoing element fades out while the incoming element fades in, creating a seamless transition experience.

### Current Behavior
Right now, it appears that the exit animation for one element completes before the enter animation of the next element begins, which prevents the smooth cross-fading effect.

### Proposed Solution
If possible, it would be great to add an option to make enter and exit animations play at the same time. This would open up new possibilities for smoother, more immersive transitions, particularly for applications where visual fluidity is essential.

**Comment by ismamz** [comment]
Hey @thmsfchtnr, you can call the `next` function whenever you prefer within the `enter` and `leave` callbacks.

Here is a ["sync" demo using Framer Motion](https://stackblitz.com/edit/next-transition-router-framer-motion-sync-demo?file=app%2Fproviders.tsx).

Keep in mind that, in some cases, the elements may not be mounted when you try to animate them.

Let me know if this is what you’re looking for.

**Comment by thmsfchtnr** [comment]
Thanks for sharing the demo! This is excactly what I was looking for haha 😅 
Appreciate the help!
