### ISSUE TITLE
Can't open a link in a new tab with keyboard shortcut

### ISSUE THREAD

**Issue by edoardolunardi** [ismamz/next-transition-router#15]
I'm a macOS user, and to quickly open a link in a new tab I usually use `CMD + click` on a link.

By looking at the code, the lib attaches a click listener on links, but it does not take into account this native shortcut, at least by using the `auto` prop on the `TransitionRouter`.

By the way, cool lib!

**Comment by ismamz** [comment]
@edoardolunardi I’ve fixed this behavior in the new version 0.2.3. Let me know if you see everything working okay now.

**Comment by edoardolunardi** [comment]
> @edoardolunardi I’ve fixed this behavior in the new version 0.2.3. Let me know if you see everything working okay now.

That fixes it! Thanks for fast push 🚗
