### ISSUE TITLE
Transition with hash link

### ISSUE THREAD

**Issue by edoardolunardi** [ismamz/next-transition-router#17]
The `TransitionRouter` with prop `auto` is now skipping hash links, since they usually point to a section within the same page. However, the current page might be `/foo` and a link could point to `/bar#section`, and in this case I would expect to see the transition as I'm navigating to a different page. 
I haven't checked the logic but a simple "no transition on hash link, only if same pathname" check should work.

**Comment by ismamz** [comment]
Hey @edoardolunardi, thanks for this feedback. I've updated the library and added this case to the demo. Try it with v0.2.6 and tell me if it works well for you.

**Comment by edoardolunardi** [comment]
> Hey @edoardolunardi, thanks for this feedback. I've updated the library and added this case to the demo. Try it with v0.2.6 and tell me if it works well for you.

Thanks for the quick addition! Works perfectly.
