### ISSUE TITLE
<Link/> href prop from nextjs should accept string or UrlObject

### ISSUE THREAD

**Issue by fadomire** [ismamz/next-transition-router#22]
Hello,

thanks for the lib,

it seems the lib `<Link/>` component does not accept `string | UrlObject` as nextjs do
https://nextjs.org/docs/app/api-reference/components/link#href-required

for example here:
https://github.com/ismamz/next-transition-router/blob/d8a407113fb972abfd0a1170f6c79e3aefd494b5/src/router.tsx#L12

**Comment by ismamz** [comment]
@fadomire I just published the new version 0.2.7 and it should work correctly now. Let me know if anything comes up!

**Comment by fadomire** [comment]
@ismamz thanks for the quick fix

it works fine now
